apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment-3
  namespace: daniel-lopez-fisa-dev
  labels:
    app: mi-app-3
    areanegocio: tecnologia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-3
  template:
    metadata:
      labels:
        app: mi-app-3
    spec:
      containers:
        - name: contenedor-principal
          image: danielopezh/oc-2:build-21  # <-- Reemplaza con la imagen que quieras usar
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
            limits:
              cpu: "400m"
              memory: "500Mi"
          startupProbe:
            httpGet:
              path: /startup
              port: 3000
            failureThreshold: 5
            periodSeconds: 10