apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dlh-hpa-3-{{ .Values.metadata.labels.app }}
  namespace: daniel-lopez-fisag-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mi-app-deployment-3-{{ .Values.metadata.labels.app }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100