apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dlh-pvc-3-{{ .Values.metadata.labels.app }}
  namespace: daniel-lopez-fisa-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: gp3