metadata:
  labels:
    app: mi-app-3

container:
  image: danielopezh/oc-2
  tag: 34
  port: 3000
  resources:
    requests:
      cpu: "200m"
      memory: "300Mi"
    limits:
      cpu: "4000m"
      memory: "500Mi"
hpa:
  minReplicas: 1
  maxReplicas: 5