name: CI-Helm-Publish

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub (Docker)
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Log in to Docker Hub (Helm OCI)
        run: helm registry login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Update version in Chart.yaml
        run: |
          sed -i "s/^version:.*/version: 0.1.${{ github.run_number }}/" ./dlh-chart/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${{ github.run_number }}\"/" ./dlh-chart/Chart.yaml
          cat ./dlh-chart/Chart.yaml

      - name: Package Helm chart
        run: |
          helm lint ./dlh-chart
          helm package ./dlh-chart
          ls -l

      - name: Push chart to Docker Hub (OCI)
        run: |
          CHART_FILE=$(ls dlh-chart-*.tgz)
          helm push $CHART_FILE oci://docker.io/${{ secrets.DOCKER_USERNAME }}/dlh-chart
